/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/9.0.0/samples
 */

plugins { base }

allprojects {
    repositories {
        mavenCentral()
        maven("https://jogamp.org/deployment/maven/") {
            metadataSources {
                mavenPom()
                artifact()
            }
        }
    }
}

subprojects {
    plugins.withType<org.gradle.api.plugins.JavaPlugin> {
        extensions.configure<org.gradle.api.plugins.JavaPluginExtension> {
            toolchain.languageVersion.set(JavaLanguageVersion.of(17))
        }
        dependencies {
            "testImplementation"("org.junit.jupiter:junit-jupiter:5.11.0")
        }
        tasks.withType<Test> { useJUnitPlatform() }
    }
}